# === Host: strato ===
[strato]
QUELLE_CONF="strato"
BACKUP_ROOT_CONF="/RAID/backup"
REMOTE_VERZEICHNISSE=(
  "/certs"
  "/etc/apache2"
  "/etc/letsencrypt"
  "/etc/docker"
  "/home/blarks"
  "/opt"
  "/srv"
  "/var/www"
  "/var/lib/docker"
)

# === Host: dockfish ===
[dockfish]
QUELLE_CONF="dockfish"
BACKUP_ROOT_CONF="/mnt/eimer/blarks/___Backup/Dockfish"
REMOTE_VERZEICHNISSE=(
  "/etc"
  "/home/blarks"
  "/opt/docker"
  "/srv"
  "/var/lib/docker"
)

# === Host: monsterklopper ===
[monsterklopper]
QUELLE_CONF="monsterklopper"
BACKUP_ROOT_CONF="/mnt/eimer/blarks/___Backup/Monsterklopper"
REMOTE_VERZEICHNISSE=(
  "/etc"
  "/home/blarks"
  "/opt"
  "/var/log"
)

# === Host: default ===
[default]
BACKUP_ROOT_CONF="/RAID/backup"
REMOTE_VERZEICHNISSE=( "/etc" "/home/blarks" "/opt" "/srv" )
