# blacksbackup.conf
# Zentrale Konfiguration für blacksbackup.sh

# === Host: strato ===
[strato]
REMOTE_VERZEICHNISSE=(
  "/certs"
  "/etc/apache2"
  "/etc/letsencrypt"
  "/etc/docker"
  "/home/blarks"
  "/opt"
  "/srv"
  "/var/www"
  "/var/lib/docker"
)

# === Host: dockfish ===
[dockfish]
REMOTE_VERZEICHNISSE=(
  "/etc"
  "/home/blarks"
  "/opt/docker"
  "/var/lib/docker"
  "/srv"
)

# === Host: monsterklopper ===
[monsterklopper]
REMOTE_VERZEICHNISSE=(
  "/etc"
  "/home/blarks"
  "/opt"
  "/var/log"
)
